"""create logs table

Revision ID: d6916eda9bb2
Revises: 
Create Date: 2026-04-05 15:17:26.009670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6916eda9bb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL')", name='logs_severity_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logs_severity', 'logs', ['severity'], unique=False)
    op.create_index('ix_logs_source', 'logs', ['source'], unique=False)
    op.create_index('ix_logs_timestamp', 'logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_timestamp', table_name='logs')
    op.drop_index('ix_logs_source', table_name='logs')
    op.drop_index('ix_logs_severity', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
